# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]

  add_tickets:
          class: LouvreBundle\Services\AddTickets
          arguments: ["@doctrine.orm.entity_manager", "@form.factory", "@session"]

  #for the stripe library
  stripe:
          class: LouvreBundle\Services\Stripe
          arguments: ['%api.publishing_key%', '%api.token%']

  #for the total of the order
  montant:
          class: LouvreBundle\Services\Montant

  order_listener:
          class: LouvreBundle\Listeners\OrderListener
          arguments: ['@montant','@mailer','@templating']
          tags:
                  - {name: doctrine.event_listener, event:prePersist}
                  - {name: doctrine.event_listener, event:postPersist}

  alaczi.twig.country_extension:
          class: alaczi\Twig\Extension\CountryExtension
          tags:
              - { name: twig.extension }

  order:
          class: LouvreBundle\Services\Order
          arguments:
              - '@doctrine.orm.entity_manager'
              - '@session'
              - '@form.factory'
              - '@templating'
              - '@mailer'
              - '@stripe'
              - '@workflow.billeterie'