# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]

  add_tickets:
          class: LouvreBundle\Services\AddTickets
          arguments: ["@doctrine.orm.entity_manager", "@form.factory", "@session"]

  modify_order:
          class: LouvreBundle\Services\modifyOrder
          arguments: ["@session"]

  final_order:
          class: LouvreBundle\Services\finalOrder
          arguments: ["doctrine.orm.entity_manager", "@session"]