<?php

namespace LouvreBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * BilletRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BilletRepository extends EntityRepository
{
    public function getBilletsByDay ()
    {
        return $this->createQueryBuilder('b')
            ->innerJoin('b.user', 'billet')
            ->addSelect('billet')
            ->where('billet.orderDate = :date')
                ->setParameter('date', new \DateTime())
            ->getQuery()
            ->getResult();
    }
}
